# Generated by Django 4.2.2 on 2023-06-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_elastic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
