# Generated by Django 4.2.2 on 2023-06-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.CharField(max_length=500),
        ),
    ]
