# Generated by Django 4.2.2 on 2023-07-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_userprofile_preferred_annual_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='min_preferred_salary_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Preferred Salary Pay'),
        ),
    ]
