# Generated by Django 4.2.2 on 2023-07-05 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_userprofile_min_preferred_salary_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='min_preferred_salary_pay',
        ),
    ]
