# Generated by Django 4.2.2 on 2023-08-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_jobapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='application_date',
            new_name='applied_at',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default='default_resume.pdf', upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(default='default_resume.pdf', upload_to='resumes/'),
        ),
    ]
